BTLcnpm/Areas/Admin/Controllers/LoginController.cs
using BTLcnpm.Areas.Admin.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Dao;
using BTLcnpm.Common;

namespace BTLcnpm.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login(LoginModel model)
        {
            //if (ModelState.IsValid)
            //{
            //    var dao = new UserDao();
            //    var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password), true);
            //    if (result == 1)
            //    {
            //        var user = dao.GetById(model.UserName);
            //        var userSession = new UserLogin();
            //        userSession.UserName = user.UserName;
            //        userSession.UserID = user.ID;

            //        Session.Add(CommonConstants.USER_SESSION, userSession);
            //        return RedirectToAction("Index", "Home");
            //    }
            //    else if (result == 0)
            //    {
            //        ModelState.AddModelError("", "Tài khoản không tồn tại.");
            //    }
            //    else if (result == -1)
            //    {
            //        ModelState.AddModelError("", "Tài khoản đang bị khoá.");
            //    }
            //    else if (result == -2)
            //    {
            //        ModelState.AddModelError("", "Mật khẩu không đúng.");
            //    }
            //    else if (result == -3)
            //    {
            //        ModelState.AddModelError("", "Tài khoản của bạn không có quyền đăng nhập.");
            //    }
            //    else
            //    {
            //        ModelState.AddModelError("", "Đăng nhập không thành công.");
            //    }
            //}
            return View("Index");
        }
    }
}

BTLcnpm/Areas/DauBepPage/Controllers/DauBepLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTLcnpm.Areas.Admin.Data;
using BTLcnpm.Areas.DauBepPage.Common;
using BTLcnpm.Areas.DauBepPage.Data;
using Model.Dao;

namespace BTLcnpm.Areas.DauBepPage.Controllers
{
    public class DauBepLoginController : Controller
    {
        // GET: DauBepPage/DauBepLogin
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(CookerLogin model)
        {
            if (ModelState.IsValid)
            {
                var dao = new CookerDao();
                var result = dao.CookerLogin(model.UserName, model.Password);
                if (result == true)
                {
                    var cooker = dao.GetCookerByUserName(model.UserName);
                    var cookerSession = new CookerLoginSession();
                    cookerSession.UserName = cooker.UserName;
                    cookerSession.VendorID = cooker.VendorId;
                    Session.Add(Constant.COOKER_SESSION, cookerSession);
                    return RedirectToAction("Index", "TrangDauBep");
                }
                else
                {
                    ModelState.AddModelError("", "Sai tài khoản hoặc mật khẩu.");
                }
            }
            return View(model);
        }
    }
}

BTLcnpm/Areas/DauBepPage/Views/DauBepLogin/Login.cshtml
@model  BTLcnpm.Areas.DauBepPage.Data.CookerLogin
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Page Title - SB Admin</title>
    <link href="~/Assets/Admin/dist/css/styles2.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                                <div class="card-body">

                                    @using (Html.BeginForm("Login", "DauBepLogin", FormMethod.Post))
                                    {
                                        @Html.ValidationSummary(false, "", new { @class = "text-danger" });
                                        <fieldset>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputEmailAddress">UserName</label>
                                                @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @autofocus = "autofocus", @id = "inputEmailAddress", @placeholder = "Nhập UserName" })
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Password</label>
                                                @Html.PasswordFor(model => model.Password, new { @class = "form-control", @id = "inputPassword", @placeholder = "Nhập password" })
                                            </div>
                                            <div class="custom-checkbox">
                                                @Html.CheckBoxFor(model => model.RememberMe, new { @id = "rememberPasswordCheck" })
                                                <label for="rememberPasswordCheck">Remember password</label>
                                            </div>

                                            <!-- Change this to a button or input when using this as a form -->
                                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <button type="submit" class="btn btn-lg btn btn-primary btn-block">Login</button>
                                            </div>
                                        </fieldset>
                                    }
                                </div>
                                <div class="card-footer text-center">
                                    <div class="small"><a href="#">Your welcome</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Assets/Admin/dist/js/scripts.js"></script>
</body>
</html>